import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import Container from '../components/Container'
import Header from '../components/header'
import { GainChart } from "../components/Charts"
import { data } from '../data/displayData'
import Summary from '../components/Summary'
import PercentageBar from '../components/PercentageBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={`${inter.className} main-container`}>
                <div>
                    <Header />
                </div>

                <div>
                    <Summary />
                </div>

                <div>
                    <div>
                        <Container title={'Gain'}>
                            <div style={{ width: '75%', height: 'inherit' }}>
                                <GainChart data={data} />
                            </div>
                            <div style={{ width: '25%', padding: '0 0 0 5%' }}>
                                <div><h4>Some Bars</h4></div>
                                <div style={{ width: '100%' }}>
                                    <div style={{ margin: 5 }}><PercentageBar max={100} value={50} label={'all'} /></div>
                                    <div style={{ margin: 5 }}><PercentageBar max={100} value={50} label={'a'} /></div>
                                    <div style={{ margin: 5 }}><PercentageBar max={100} value={50} label={'a'} /></div>
                                    <div style={{ margin: 5 }}><PercentageBar max={100} value={50} label={'a'} /></div>
                                </div>
                            </div>
                        </Container>
                    </div>
                </div>

                <div>
                    <Container>
                        <GainChart data={data} />
                    </Container>
                </div>
            </main>
        </>
    )
}
