import Head from 'next/head'
import { Inter } from '@next/font/google'
import NavBar from '../components/NavBar'
import Container from '../components/Container'
import Header from '../components/Header'
import { GainChart } from "../components/Charts"
import { data } from '../data/displayData'
import Summary from '../components/Summary'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div style={{ position: 'fixed', top: 0, bottom: 0 }}>
                <NavBar />
            </div>

            <main className={inter.className} style={{ margin: '15px 20px 0 75px' }}>
                <div>
                    <Header />
                </div>

                <div>
                    <Summary />
                </div>

                <div>
                    <div>
                        <Container>
                            <GainChart data={data} />
                        </Container>
                    </div>
                </div>

                <div>
                    <Container>
                        <GainChart data={data} />
                    </Container>
                </div>
            </main>
        </>
    )
}
